# visualize with 40 primary tracks

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/vis/verbose 0

/control/execute process_setup.mac


/vis/open OGL 800x1000

/vis/drawVolume


/vis/viewer/set/style wireframe
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/vis/geometry/set/lineWidth all -1 2

/vis/viewer/set/viewpointVector -1 -1.1 0.5
/vis/viewer/set/upVector 0 0 1

